### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by killarneyman** [tightenco/react-gif-search-engine#1]
The tutorial is great, but it all seemed to fall apart for me at the end of Step 10.

It stopped rendering anything, and the only error I get is the cryptic

`bundle.js:29196 Uncaught TypeError: Cannot read property 'apply' of undefined`

I have also tried cloning your repo to see if I had made a typo, but that results in the same error.

npm 2.13.1, node 4.4.3, windows 10. I'll give it a shot later on one of my linux machines and see if it's an OS issue.

**Comment by samanthamichele7** [comment]
Hmm, definitely keep me updated once you try it on a Unix-based machine. I'm not using "apply" anywhere in my codebase, so it's likely a package bug (especially since I'm on npm 3.6.0 / node 5.5.0).

It's possible that you're falling victim to the same bug as the folks in this thread, perhaps? https://github.com/webpack/webpack/issues/959#issuecomment-199835414

They seem to have had some luck with setting `cache: false` in the webpack config -- maybe it's something else to try if you're not having luck on Linux?

Let me know! :)

**Comment by killarneyman** [comment]
Nothing in that link helped unfortunately, after much digging, and commenting out lines one by one, I narrowed it down to being caused by the call to compose() in configureStore.

Removing
`window.devToolsExtension ? window.devToolsExtension() : undefined`

allows the app to load, and it seems to function fine. I ave no idea _why_ this is causing the error, that line was working fine before the switch to compose (When the ReduxPromise middle-ware was added in step 10.)

**Comment by killarneyman** [comment]
I solved it, and submitted a pull request with a fix & explanation.

Keep in mind, when verifying this fix, you can only reproduce this error by either setting the second argument of compose as undefined, or by using a browser without react devtools installed.

Once again, thanks for the great tutorial.

**Comment by samanthamichele7** [comment]
Nice sleuthing work! :) I poked around the Redux Dev tools docs, and it looks like `window.devToolsExtension ? window.devToolsExtension() : undefined` works until you have other store enhancers or middleware (such as ReduxPromise) installed, at which point you need `  window.devToolsExtension ? window.devToolsExtension() : f => f` -- which is why it specifically broke on step 10.

Thank you so much for catching this bug and submitting a fix! I originally had [Redux dev tools](https://github.com/gaearon/redux-devtools) set up as a component in the code and decided at the last minute to switch to the Chrome extension to simplify things. This bug slipped right past my testing.

Instead of merging your PR in to master directly, I'm going to update the tutorial and do some editing directly on the commits so this issue doesn't pop up for anyone else. Thanks again!
